### ISSUE TITLE
NoteWrangler on windows.

### ISSUE THREAD

**Issue by xipxoom** [codeschool/NoteWrangler#10]
@jonfriskics, I just got finished helping someone from the codeschool forums get this running on windows with node v5.4.1 and it was a bit of a fight.  You can see our conversation here: http://discuss.codeschool.io/t/unable-to-install-the-demo-code-in-github/22956

In the end I just had to bump the sqlite3 version to the latest and exchanged bcrypt for bcryptjs in the dependencies and app/server/modules/encrypt.js.  What do you think about making these changes to this here?

**Comment by jonfriskics** [comment]
I'll let our Angular people know about it and see what we can get fixed.  Thanks for bringing this to our attention and helping other people on the forums!

**Comment by renz45** [comment]
Hi there, sorry about this, I must have had notifications turned off for some reason for this repo :( I've updated everything to work on node 5.5. Added a nvmrc as well to be a bit more specific about which version of node works.
