### ISSUE TITLE
failed  postinstall: `node dbSeed.js` on linux

### ISSUE THREAD

**Issue by sandernelen** [codeschool/NoteWrangler#4]
npm install error:
npm ERR! note-wrangler@0.0.0 postinstall: `node dbSeed.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the note-wrangler@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the note-wrangler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dbSeed.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls note-wrangler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/sander/WebstormProjects/NoteWrangler
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sander/WebstormProjects/NoteWrangler/npm-debug.log
npm ERR! not ok code 0

Can anyone fix this?

**Comment by renz45** [comment]
Going to close this since its so old. I apologize for not responding at the time. My notifications for this repo were turned off for some reason. Feel free to resubmit if its still an issue and I'll see the issue this time. :)
