### ISSUE TITLE
npm start doesn't work and throws error

### ISSUE THREAD

**Issue by chann1283** [codeschool/NoteWrangler#7]
## Hi, I am start server but getting following bcrypt error but when i try to install bcrypt it further does not installs bcrypt. I am new to node js please help.

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler\app\server\modules\encrypt.js:2:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! note-wrangler@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the note-wrangler@0.0.0 start script 'node app.js'.
## npm ERR! This is most likely a problem with the note-wrangler package,

npm install bcrypt gives following error

---

E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler [master]> npm install bcrypt
/

> bcrypt@0.8.2 install E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler\node_modules\bcrypt
> node-gyp rebuild

E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio
2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler\node_mo
dules\bcrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\sunny\Self study\ANGULAR JS\CODE SCHOOL\project\NoteWrangler\node_modules\bcrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "bcrypt"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.

**Comment by renz45** [comment]
I apologize for not responding to this issue, I had notifications turned off for this repo. Everything should work on node 5.5 now. The issue was updating the sqlite3 and bcrypt node modules.
